version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5400:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: newShop
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  default:
    name: postgre-service_default
    